### ISSUE TITLE
ZIP file displayed nicely

### ISSUE THREAD

**Issue by kgdunn** [scipy/SciPyCentral#107]
Icons for directory, basic MIME types

* http://www.filamentgroup.com/examples/menus/flyout.php
* http://www.filamentgroup.com/lab/jquery_ipod_style_and_flyout_menus/
* http://wiki.jqueryui.com/w/page/12137997/Menu
* http://jdsharp.us/jQuery/plugins/jdMenu/
* http://jquery.bassistance.de/treeview/demo/async.html
* http://www.adventuresindevelopment.com/2009/05/19/how-to-create-a-jquery-file-browser-with-jquery-file-tree/
* http://www.filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/
* http://stackoverflow.com/questions/2010391/jquery-select-plugin-that-will-allow-for-folder-file-structured-tiered-options

**Comment by ksurya** [comment]
This enhancement is done: https://github.com/scipy/SciPyCentral/pull/188
