### ISSUE TITLE
short domain for permalinks does not work: ad site shows up

### ISSUE THREAD

**Issue by gauteh** [scipy/SciPyCentral#153]
http://scpyce.org/ does not seem to work, redirects to some ad / parked domain site.

**Comment by gauteh** [comment]
The domain does not resolve, links on main page still refer to this domain.

**Comment by ksurya** [comment]
@pv I think we need to fix this asap

**Comment by gauteh** [comment]
Links still refer to spyce, get rid of the short permalinks for the time being?

**Comment by ksurya** [comment]
https://github.com/scipy/SciPyCentral/pull/194

Fixed
